WebShop/WebShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebShop.Models;
using Newtonsoft.Json;

namespace WebShop.Controllers
{
    /// <summary>
    /// This class defines a controller for managing a user's shopping cart.
    /// </summary>
    public class CartController : Controller
    {
        /// <summary>
        /// This method handles HTTP GET requests to the myCart route, and
        /// returns a view that shows the items in the user's cart.
        /// </summary>
        /// <returns>A view that displays the items in the user's cart.</returns>
        [Route("myCart")]
        [HttpGet]
        public ActionResult CartView()
        {
            List<OrderLine> orders;
            ModelCartView mcv = new();

            if (HttpContext.Session.GetString("OrderLines") != null)
            {
                orders = JsonConvert.DeserializeObject<List<OrderLine>>(HttpContext.Session.GetString("OrderLines"));
            }
            else
            {
                orders = new List<OrderLine>();
            }
            mcv.OrderLines = orders;
            mcv.Loggedin = HttpContext.User.Identity.IsAuthenticated && (HttpContext.User != null);

            return View(mcv);
        }

        /// <summary>
        /// This action method updates the quantity of an item in the cart.
        /// </summary>
        /// <param name="quantity">The updated quantity of the item.</param>
        /// <param name="id">The id of the item to be updated.</param>
        /// <returns>The updated cart view.</returns>
        [Route("myCart")]
        [HttpPost]
        public ActionResult CartView(int quantity, int id)
        {
            // Deserialize the order lines from the session
            List<OrderLine> orders = JsonConvert.DeserializeObject<List<OrderLine>>(HttpContext.Session.GetString("OrderLines"));
            ModelCartView mcv = new();

            // Update the quantity of the item with the specified id
            foreach (var item in orders)
            {
                if (item.Product.id == id)
                {
                    item.Quantity = quantity;
                }

            }
            mcv.OrderLines = orders;
            // Check if the user is logged in
            mcv.Loggedin = HttpContext.User.Identity.IsAuthenticated && (HttpContext.User != null);
            // Serialize the updated order lines and store them in the session
            string JsonOrderLines = JsonConvert.SerializeObject(orders);
            HttpContext.Session.SetString("OrderLines", JsonOrderLines);

            return View(mcv);
        }

        /// <summary>
        /// This action method displays the details of an item in the cart.
        /// </summary>
        /// <param name="id">The id of the item to display the details for.</param>
        /// <returns>The details view of the specified item.</returns>
        public ActionResult Details(int id)
        {
            return View();
        }

        /// <summary>
        /// This action method displays the view for creating a new item in the cart.
        /// </summary>
        /// <returns>The create view.</returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// This action method creates a new item in the cart.
        /// </summary>
        /// <param name="collection">The form collection containing the details of the item to be added to the cart.</param>
        /// <returns>The index view if the item is successfully added, the create view otherwise.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// This action method displays the view for editing an item in the cart.
        /// </summary>
        /// <param name="id">The id of the item to be edited.</param>
        /// <returns>The edit view for the specified item.</returns>
        public ActionResult Edit(int id)
        {
            return View();
        }

        /// <summary>
        /// This action method edits an existing item in the cart.
        /// </summary>
        /// <param name="id">The id of the item to be edited.</param>
        /// <param name="collection">The form collection containing the updated details of the item.</param>
        /// <returns>The index view if the item is successfully edited, the edit view otherwise.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// This action method displays the view for deleting an item from the cart.
        /// </summary>
        /// <param name="id">The id of the item to be deleted.</param>
        /// <returns>The delete view for the specified item.</returns>
        public ActionResult Delete(int id)
        {
            return View();
        }

        /// <summary>
        /// This action method deletes an item from the cart.
        /// </summary>
        /// <param name="id">The id of the item to be deleted.</param>
        /// <param name="collection">The form collection containing the details of the item to be deleted.</param>
        /// <returns>The index view if the item is successfully deleted, the delete view otherwise.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebShop/WebShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop.Models;
using Newtonsoft.Json;
using WebShop.LogicControllers;

using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;


namespace WebShop.Controllers
{
    /// <summary>
    /// This controller is responsible for handling requests related to orders in the web shop.
    /// </summary>
    public class OrderController : Controller
    {
        private OrderLogicController _OrderLogicController = new();

        private readonly UserManager<IdentityUser> _userManager;

        /// <summary>
        /// Initializes a new instance of the `OrderController` class.
        /// </summary>
        /// <param name="userManager">The `UserManager` instance used to retrieve user information.</param>
        public OrderController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        /// <summary>
        /// Returns a view of the current sale order, including information about the order lines
        /// and the customer who placed the order.
        /// </summary>
        /// <returns>An IActionResult representing the view of the current sale order.</returns>
        public IActionResult OrderView()
        {
            ModelOrderView mov = new ModelOrderView();
            mov.orderLines = JsonConvert.DeserializeObject<List<OrderLine>>(HttpContext.Session.GetString("OrderLines"));
            var user = _userManager.FindByNameAsync(HttpContext.User.Identity.Name).Result;
            
            Customer c = CustomerLogicController.GetCustomerFromAPIByEmail(user.Email);
            if (c.userID == null)
            {
                mov.customer.Email = user.Email;
                mov.customer.userID = user.Id;
            }
            else
                mov.customer = c;

            return View(mov);
        }

        /// <summary>
        /// Handles a POST request for the sale order view. Adds customer information from the request
        /// to the sale order object and saves the sale order to the database.
        /// </summary>
        /// <param name="_MOV">The SaleOrder object to be updated and saved.</param>
        /// <returns>An IActionResult representing the updated sale order view.</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> OrderView(ModelOrderView _MOV)
        {       
            _MOV.orderLines = JsonConvert.DeserializeObject<List<OrderLine>>(HttpContext.Session.GetString("OrderLines"));
            var user = _userManager.FindByNameAsync(HttpContext.User.Identity.Name).Result;

            bool val1 = (HttpContext.User != null) && HttpContext.User.Identity.IsAuthenticated;

            bool status = false;
            if (val1)
            {
               status = _OrderLogicController.AddSaleOrderToDB(_MOV, user);
            }

            if (status)
            {
                return RedirectToAction("OrderConfirmationView", _MOV);
            }else
                return View("Error");
        }

        [Authorize]
        public async Task<IActionResult> OrderConfirmationView(ModelOrderView _MOV)
        {
            HttpContext.Session.SetString("OrderLines", JsonConvert.SerializeObject(new List<OrderLine>()));
            return View(_MOV);
        }
    }
}

WebShop/WebShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop.Models;
using WebShop.LogicControllers;
using WebShop.ServiceLayer;

namespace WebShop.Controllers
{
    /// <summary>
    /// The ProductController class is derived from the Controller class.
    /// It contains methods for handling product-related actions in the web application.
    /// </summary>
    public class ProductController : Controller
    {

        private ProductLogicController _ProductLogicController;
        private OrderLineLogicController OrderLineLogicController;

        /// <summary>
        /// Constructor for the ProductController that takes in an IConfiguration object
        /// </summary>
        /// <param name="inConfiguration">The IConfiguration object to use</param>
        public ProductController(IConfiguration inConfiguration)
        {
            OrderLineLogicController = new OrderLineLogicController(inConfiguration);
            _ProductLogicController = new ProductLogicController(inConfiguration);
        }

        /// <summary>
        /// The Index ActionResult for the ProductController
        /// </summary>
        /// <returns>A ViewResult object</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Gets a list of products from the ProductLogicController's GetProductsFromService method
        /// </summary>
        public IActionResult ProductsView()
        {
            List<Product> products = _ProductLogicController.GetProductsFromService();
            return View(products);
        }

        // <summary>
        /// Gets a single product from the ProductLogicController's GetProductFromServiceByID method
        /// </summary>
        public IActionResult ProductView(int id)
        {
            Product pp = _ProductLogicController.GetProductFromServiceByID(id);
            return View(pp);
        }

        /// <summary>
        /// This method receives an ID and uses it to retrieve a list of products.
        /// </summary>
        /// <param name="id">The ID of the product to retrieve.</param>
        /// <returns>A view of the retrieved products.</returns>
        [HttpPost]
        public IActionResult ProductsView(int id) 
        { 
            HttpContext http = HttpContext;
            List<Product> products = _ProductLogicController.AddProductToCart(id, http);
            return View(products);
        }

        /// <summary>
        /// This method receives a Product object as input and adds it to an order.
        /// </summary>
        /// <param name="_Product">The Product to add to the order.</param>
        /// <returns>A view of the updated product.</returns>
        [HttpPost]
        public IActionResult ProductView(Product _Product)
        {
            HttpContext http = HttpContext;
            Product product = _ProductLogicController.addProductToOrder(_Product, http);
            return View(product);
        }
    }
}

WebShop/WebShop/Views/Cart/CartView.cshtml
@using WebShop.Models;
@model ModelCartView;

@{
    ViewData["Title"] = "Indkøbskurv";
}

<section class="h-100 h-custom" style="background-color: #d2c9ff;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12">
                <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                    <div class="card-body p-0">
                        <div class="row g-0">
                            <div class="col-lg-8">
                                <div class="p-5">
                                    <div class="d-flex justify-content-between align-items-center mb-5">
                                        <h1 class="fw-bold mb-0 text-black">Indkøbskurv</h1>
                                        <h6 class="mb-0 text-muted">Antal af produkter:  @Model.OrderLines.Count</h6>
                                    </div>


                                    @foreach (var item in Model.OrderLines)
                                    {
                                        <hr class="my-4">

                                        <div class="row mb-4 d-flex justify-content-between align-items-center">
                                            <div class="col-md-2 col-lg-2 col-xl-2">
                                                <img src=""
                                                 class="img-fluid rounded-3" alt="@item.Product.Title">
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-3">
                                                <h6 class="text-muted">@item.Product.Title</h6>
                                                <h6 class="text-black mb-0">@item.Product.ProductDesc</h6>
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-2 d-flex">

                                                @using (Html.BeginForm("CartView", "Cart", FormMethod.Post))
                                                {

                                                    <input id="form1" min="1" name="quantity" value="@item.Quantity" type="number"
                                                   class="form-control form-control-sm" onchange="SetNewQuantity();" />


                                                    <input id="form2" min="1" name="id" value="@item.Product.id" type="number"
                                                   class="form-control form-control-sm" hidden="hidden" />

                                                    <input type="submit" value="Tilføj" />
                                                }

                                            </div>
                                            <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                <h6 class="mb-0"> @item.CalcSubTotal() DKK</h6>
                                            </div>
                                            <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                                <a href="#!" class="text-muted"><i class="fas fa-times"></i></a>
                                            </div>
                                        </div>

                                        <hr class="my-4">

                                    }

                                    <div class="pt-5">
                                        <h6 class="mb-0">
                                            <a href="@Url.Action("ProductsView", "Product")" class="text-body">
                                                <i class="fas fa-long-arrow-alt-left me-2"></i>Tilbage til produkt oversigt
                                            </a>
                                        </h6>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 bg-grey">
                                <div class="p-5">
                                    <h3 class="fw-bold mb-5 mt-2 pt-1">Oversigt</h3>
                                    <hr class="my-4">

                                    <div class="d-flex justify-content-between mb-4">
                                        <h5 class="text-uppercase">Subtotal</h5>
                                        <h5>@Model.CalcSubTotal() DKK</h5>
                                    </div>


                                    <h5 class="text-uppercase mb-3">Rabat kode:</h5>

                                    <div class="mb-5">
                                        <div class="form-outline">
                                            <input type="text" id="form3Examplea2" class="form-control form-control-lg" />
                                            <label class="form-label" for="form3Examplea2">Skriv din kode her</label>
                                        </div>
                                    </div>

                                    <hr class="my-4">

                                    <div class="d-flex justify-content-between mb-5">
                                        <h5 class="text-uppercase">Total pris </h5>


                                        <h5> @Model.CalcSubTotal() DKK</h5>
                                    </div>
                                    @if (Model.Loggedin && Model.OrderLines.Count > 0)
                                    {
                                        <button class="btn btn-primary btn-sm" type="button" onclick="location.href='@Url.Action("OrderView", "Order")'">Gå til betaling</button>

                                    }
                                    else if (Model.Loggedin && Model.OrderLines.Count <= 0)
                                    {
                                        <button class="btn btn-primary btn-sm" type="button" onclick="location.href='@Url.Content("Product/ProductsView")'">Gå til betaling</button>
                                    }
                                    else
                                    {
                                        <button class="btn btn-primary btn-sm" type="button" onclick="location.href='@Url.Content("Identity/Account/Login")'">Gå til betaling</button>
                                    }

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">


    function SetNewQuantity() {

        var NewQuantity = document.getElementById('form1').value;
        $('#myCart').val(NewQuantity);
        $('')

    }

    function SendId() {

        var id = document.getElementById('form2').value;
        $('#myCart').val(id);


    }


</script>